/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2014-08-24 13:50:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.src;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.myhome.univ.*;
import java.util.ArrayList;

public final class board_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/src/./include/writeModal.jsp", Long.valueOf(1408888186913L));
    _jspx_dependants.put("/src/./include/header.jsp", Long.valueOf(1408887926444L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\n");
      out.write("\n");

	request.setCharacterEncoding("EUC-KR");

	//로그인 체크
	String userid = (String) session.getAttribute("userid");
	String username = (String) session.getAttribute("username");

	//현재 페이지의 파일명 체크

	String cururl = request.getRequestURI().toString();
	String pageName = cururl.substring(cururl.lastIndexOf("/") + 1,
			cururl.length());
	session.setAttribute("pageName", pageName);

	System.out.println(pageName);

	if ((!pageName.equals("index.jsp")) && !pageName.equals("")) {
		if (userid == null) {

      out.write("\n");
      out.write("<script>\n");
      out.write("\talert(\"로그인이 필요한 서비스입니다\");\n");
      out.write("\tlocation.href = \"./index.jsp\";\n");
      out.write("</script>\n");

	}
	}

      out.write("\n");
      out.write("\n");
      out.write("<!-- 페이지 헤더 : 시작 -->\n");
      out.write("<div class=\"bs-header\" id=\"content\">\n");
      out.write("\t<div class=\"marketing-section marketing-section-signup\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"col-lg-12\">\n");
      out.write("\t\t\t\t<h1 class=\"heading\" style=\"font-family: 'Nanum Pen Script', serif;\">대학생들을\n");
      out.write("\t\t\t\t\t위한 중고시장</h1>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<!-- 페이지 헤더 : 끝 -->\n");
      out.write("\n");
      out.write("<!-- 네비게이션바 : 시작 -->\n");
      out.write("<nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"navbar-header\">\n");
      out.write("\t\t\t<!-- 모바일 크기일 때 네비게이션바를 한버튼으로 몰아 넣는 기능(타겟의 id값에 해당되는 목록을 출력해준다) -->\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\n");
      out.write("\t\t\t\tdata-target=\"#bs-example-navbar-collapse-1\">\n");
      out.write("\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span>\n");
      out.write("\t\t\t</button>\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"./index.jsp\">HOME</a>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<!-- id를 주어 자바스크립트로 모바일 화면에서 네비바버튼이 동작되게 한다 -->\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\"\n");
      out.write("\t\t\tid=\"bs-example-navbar-collapse-1\">\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\n");
      out.write("\t\t\t\t<li><a href=\"#\"><small>전국중고시장</small></a></li>\n");
      out.write("\t\t\t\t<li><a href=\"./board.jsp\"><small>대학중고시장</small></a></li>\n");
      out.write("\t\t\t\t<li><a href=\"#\"><small>무료나눔</small></a></li>\n");
      out.write("\t\t\t\t<li><a href=\"#\"><small>알바모집</small></a></li>\n");
      out.write("\t\t\t\t<li><a href=\"#\"><small>원룸광고</small></a></li>\n");
      out.write("\t\t\t\t<li><a href=\"#\"><small>고객센터</small></a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t\t\t<!-- 자바스크립트로 if문을 사용하여 로그인되었는지 안되었는지를 구분 -->\n");
      out.write("\t\t\t\t");

					//로그인이 되어있으면
					if (userid != null && !userid.equals("")) {
				
      out.write("\n");
      out.write("\t\t\t\t<li><a href=\"#\"> <span class=\"glyphicon glyphicon-user\"></span>&nbsp;<small>");
      out.print(username);
      out.write("&nbsp;님</small>\n");
      out.write("\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"#\"> <span class=\"glyphicon glyphicon-send\"></span>&nbsp;<small>&nbsp;쪽지</small>\n");
      out.write("\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"./logout_proc.jsp\"> <span\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-out\"></span>&nbsp;<small>로그아웃</small>\n");
      out.write("\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t");

					//로그인이 되어있지 않다면
					} else {
				
      out.write("\n");
      out.write("\t\t\t\t<li><a data-toggle=\"modal\" href=\"#loginModal\"> <span\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-in\"></span>&nbsp;<small>로그인</small>\n");
      out.write("\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t<li><a data-toggle=\"modal\" href=\"#joinModal\"> <span\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-plus\"></span>&nbsp;<small>회원가입</small>\n");
      out.write("\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</nav>\n");
      out.write("<!-- 네비게이션바 : 끝 -->\n");
      out.write("\n");
      out.write("<!-- 로그인모달 : 시작 -->\n");
      out.write("<div class=\"modal fade\" id=\"loginModal\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("\taria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("\t<form name=\"login_form\" method=\"post\" class=\"form-horizontal\"\n");
      out.write("\t\trole=\"form\">\n");
      out.write("\t\t<input type=\"hidden\" name=\"pageName\" value=");
      out.print(pageName);
      out.write(">\n");
      out.write("\t\t<div class=\"modal-dialog\">\n");
      out.write("\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("\t\t\t\t\t\taria-hidden=\"true\">×</button>\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\">\n");
      out.write("\t\t\t\t\t\t<span class=\"glyphicon glyphicon-log-in\"></span>&nbsp;LOGIN\n");
      out.write("\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"inputId\" class=\"col-lg-3 control-label\">회원 ID</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-6\">\n");
      out.write("\t\t\t\t\t\t\t<input name=\"userid\" type=\"text\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"User ID\" tabindex=\"1\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-3\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" tabindex=\"4\"><h6>아이디 찾기</h6></a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"inputPassword1\" class=\"col-lg-3 control-label\">비밀번호</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-6\">\n");
      out.write("\t\t\t\t\t\t\t<input name=\"password\" type=\"password\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Password\" tabindex=\"2\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-3\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" tabindex=\"5\"><h6>비밀번호 찾기</h6></a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\"\n");
      out.write("\t\t\t\t\t\ttabindex=\"6\">취소</button>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\"\n");
      out.write("\t\t\t\t\t\tonclick=\"login_check()\" tabindex=\"3\">로그인</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</form>\n");
      out.write("</div>\n");
      out.write("<!-- 로그인모달 : 끝 -->\n");
      out.write("\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/style-kustom.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./assets/css/docs.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery Version 1.11.0 -->\r\n");
      out.write("<script src=\"./js/jquery-1.11.0.js\"></script>\r\n");
      out.write("<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("<script src=\"./js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- script -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/member.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/board.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		String opt = request.getParameter("options");
		String univOpt = request.getParameter("univOpt");
		String boardOpt = request.getParameter("boardOpt");

		System.out.println(opt);
		System.out.println(univOpt);
		System.out.println(boardOpt);
	
      out.write("\r\n");
      out.write("\t<form name=\"form\" method=\"get\">\r\n");
      out.write("\t\t<!-- 페이지 바디 : 시작 -->\r\n");
      out.write("\t\t<div class=\"container bs-docs-container\">\r\n");
      out.write("\t\t\t<!-- 게시판 리스트 헤더 : 시작 -->\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"row page-header\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-1\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"btn-group btn-group-sm col-md-2\" data-toggle=\"buttons\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"btn btn-warning\"> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"options\" value=\"1\">팝니다\r\n");
      out.write("\t\t\t\t\t\t</label> <label class=\"btn btn-warning\"> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"options\" value=\"2\">삽니다\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"univOpt\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>----- 대학선택 -----</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								univDao dao = new univDao();
								ArrayList<univDto> list = new ArrayList<univDto>();
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<optgroup label=\"<ㄱ>\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t");

								list = (ArrayList) dao.getList("가", "나");
								for (int i = 0; i < list.size(); i++) {
									univDto dto = list.get(i);
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(dto.getUnivname());
      out.write('"');
      out.write('>');
      out.print(dto.getUnivname());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<optgroup label=\"\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<optgroup label=\"<ㄴ>\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t");

								list = (ArrayList) dao.getList("나", "다");
								for (int i = 0; i < list.size(); i++) {
									univDto dto = list.get(i);
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(dto.getUnivname());
      out.write('"');
      out.write('>');
      out.print(dto.getUnivname());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<optgroup label=\"\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<optgroup label=\"<ㄷ>\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t");

								list = (ArrayList) dao.getList("다", "라");
								for (int i = 0; i < list.size(); i++) {
									univDto dto = list.get(i);
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(dto.getUnivname());
      out.write('"');
      out.write('>');
      out.print(dto.getUnivname());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<optgroup label=\"\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<optgroup label=\"<ㄹ>\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t");

								list = (ArrayList) dao.getList("라", "마");
								for (int i = 0; i < list.size(); i++) {
									univDto dto = list.get(i);
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(dto.getUnivname());
      out.write('"');
      out.write('>');
      out.print(dto.getUnivname());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<optgroup label=\"\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<optgroup label=\"<ㅁ>\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t");

								list = (ArrayList) dao.getList("마", "바");
								for (int i = 0; i < list.size(); i++) {
									univDto dto = list.get(i);
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(dto.getUnivname());
      out.write('"');
      out.write('>');
      out.print(dto.getUnivname());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<optgroup label=\"\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<optgroup label=\"<ㅂ>\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t");

								list = (ArrayList) dao.getList("바", "사");
								for (int i = 0; i < list.size(); i++) {
									univDto dto = list.get(i);
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(dto.getUnivname());
      out.write('"');
      out.write('>');
      out.print(dto.getUnivname());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("<optgroup label=\"\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<optgroup label=\"<ㅅ>\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t");

								list = (ArrayList) dao.getList("사", "아");
								for (int i = 0; i < list.size(); i++) {
									univDto dto = list.get(i);
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(dto.getUnivname());
      out.write('"');
      out.write('>');
      out.print(dto.getUnivname());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("<optgroup label=\"\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<optgroup label=\"<ㅇ>\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t");

								list = (ArrayList) dao.getList("아", "자");
								for (int i = 0; i < list.size(); i++) {
									univDto dto = list.get(i);
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(dto.getUnivname());
      out.write('"');
      out.write('>');
      out.print(dto.getUnivname());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("<optgroup label=\"\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<optgroup label=\"<ㅈ>\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t");

								list = (ArrayList) dao.getList("자", "차");
								for (int i = 0; i < list.size(); i++) {
									univDto dto = list.get(i);
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(dto.getUnivname());
      out.write('"');
      out.write('>');
      out.print(dto.getUnivname());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("<optgroup label=\"\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<optgroup label=\"<ㅊ>\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t");

								list = (ArrayList) dao.getList("차", "카");
								for (int i = 0; i < list.size(); i++) {
									univDto dto = list.get(i);
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(dto.getUnivname());
      out.write('"');
      out.write('>');
      out.print(dto.getUnivname());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("<optgroup label=\"\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<optgroup label=\"<ㅋ>\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t");

								list = (ArrayList) dao.getList("카", "타");
								for (int i = 0; i < list.size(); i++) {
									univDto dto = list.get(i);
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(dto.getUnivname());
      out.write('"');
      out.write('>');
      out.print(dto.getUnivname());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("<optgroup label=\"\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<optgroup label=\"<ㅍ>\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t");

								list = (ArrayList) dao.getList("파", "하");
								for (int i = 0; i < list.size(); i++) {
									univDto dto = list.get(i);
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(dto.getUnivname());
      out.write('"');
      out.write('>');
      out.print(dto.getUnivname());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("<optgroup label=\"\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<optgroup label=\"<ㅎ>\"></optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t");

								list = (ArrayList) dao.getList("하", "하");
								for (int i = 0; i < list.size(); i++) {
									univDto dto = list.get(i);
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(dto.getUnivname());
      out.write('"');
      out.write('>');
      out.print(dto.getUnivname());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"boardOpt\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>---- 게시판선택 ----</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"직거래\">직거래</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"안전거래\">안전거래</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-1\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-success\" value=\"검색\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"boardCheck()\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-1\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 게시판리스트 뷰어 옵션버튼\r\n");
      out.write("\t\t\t\t<div class=\"navbar-right radio\">\r\n");
      out.write("\t\t\t\t\t<label> <input type=\"radio\" name=\"optionsRadios\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"op_album\"> <small><span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-th-large\"></span>&nbsp;앨범형</small></label> &nbsp; <label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"optionsRadios\" value=\"op_board\"\r\n");
      out.write("\t\t\t\t\t\tchecked=\"checked\"> <small><span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-align-justify\"> </span>&nbsp;게시글형</small>\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 게시판 리스트 헤더 : 끝 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 게시판 리스트 바디 : 시작 -->\r\n");
      out.write("\t\t\t<div class=\"container bs-docs-container\">\r\n");
      out.write("\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t<table class=\"table table-condensed table-hover\">\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"70\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"*\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"170\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"70\">\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"text-center\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"font-weight: bolder; background-image: url('./images/table_mid.gif');\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>번호</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>제목</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>작성자</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>작성일</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>조회수</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\">1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\"><a href=\"#\">제목1</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\"><a href=\"#\">작성자1</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\">2014-08-15</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\">30</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 게시판 리스트 바디 : 끝 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 게시판 리스트 아래 글쓰기, 검색, 페이징 : 시작 -->\r\n");
      out.write("\t\t\t<div class=\"row text-center\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t<input class=\"btn btn-primary navbar-right\" type=\"button\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"글쓰기\" data-toggle=\"modal\" data-target=\"#writeModal\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"pagination\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">&laquo;</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"#\">1</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">2</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">3</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">4</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">5</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">&raquo;</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\">&nbsp;<input\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-primary btn-sm\" type=\"button\" value=\"검색\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 게시판 리스트 아래 글쓰기, 검색, 페이징 : 끝 -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 페이지 바디 : 끝 -->\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<!-- 꼬릿말 : 시작 -->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t<p>Copyright &copy; Your Website 2014</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 꼬릿말 : 끝 -->\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 글쓰기모달 : 시작 -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"writeModal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\t\taria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<form name=\"write_form\" method=\"post\" class=\"form-horizontal\"\r\n");
      out.write("\t\t\trole=\"form\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\taria-hidden=\"true\">×</button>\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"modal-title\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-pencil\"></span>&nbsp;WRITE\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"control-label\">카테고리</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">구분</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"sell\">팝니다</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"buy\">삽니다</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">학교선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"board_sell\">벼룩시장(팝니다)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"board_buy\">벼룩시장(삽니다)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"room_board\">원룸정보</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"control-label\">제목</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"제목을 입력하세요\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"control-label\">내용</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea class=\"form-control\" style=\"height: 180px\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"control-label\">첨부파일</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"file\" class=\"control-label\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">취소</button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\">작성완료</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 글쓰기모달 : 끝 -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
