/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2014-08-24 13:50:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.src;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class event_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/src/./include/header.jsp", Long.valueOf(1408887926444L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\n");
      out.write("\n");

	request.setCharacterEncoding("EUC-KR");

	//로그인 체크
	String userid = (String) session.getAttribute("userid");
	String username = (String) session.getAttribute("username");

	//현재 페이지의 파일명 체크

	String cururl = request.getRequestURI().toString();
	String pageName = cururl.substring(cururl.lastIndexOf("/") + 1,
			cururl.length());
	session.setAttribute("pageName", pageName);

	System.out.println(pageName);

	if ((!pageName.equals("index.jsp")) && !pageName.equals("")) {
		if (userid == null) {

      out.write("\n");
      out.write("<script>\n");
      out.write("\talert(\"로그인이 필요한 서비스입니다\");\n");
      out.write("\tlocation.href = \"./index.jsp\";\n");
      out.write("</script>\n");

	}
	}

      out.write("\n");
      out.write("\n");
      out.write("<!-- 페이지 헤더 : 시작 -->\n");
      out.write("<div class=\"bs-header\" id=\"content\">\n");
      out.write("\t<div class=\"marketing-section marketing-section-signup\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"col-lg-12\">\n");
      out.write("\t\t\t\t<h1 class=\"heading\" style=\"font-family: 'Nanum Pen Script', serif;\">대학생들을\n");
      out.write("\t\t\t\t\t위한 중고시장</h1>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<!-- 페이지 헤더 : 끝 -->\n");
      out.write("\n");
      out.write("<!-- 네비게이션바 : 시작 -->\n");
      out.write("<nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"navbar-header\">\n");
      out.write("\t\t\t<!-- 모바일 크기일 때 네비게이션바를 한버튼으로 몰아 넣는 기능(타겟의 id값에 해당되는 목록을 출력해준다) -->\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\n");
      out.write("\t\t\t\tdata-target=\"#bs-example-navbar-collapse-1\">\n");
      out.write("\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span>\n");
      out.write("\t\t\t</button>\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"./index.jsp\">HOME</a>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<!-- id를 주어 자바스크립트로 모바일 화면에서 네비바버튼이 동작되게 한다 -->\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\"\n");
      out.write("\t\t\tid=\"bs-example-navbar-collapse-1\">\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\n");
      out.write("\t\t\t\t<li><a href=\"#\"><small>전국중고시장</small></a></li>\n");
      out.write("\t\t\t\t<li><a href=\"./board.jsp\"><small>대학중고시장</small></a></li>\n");
      out.write("\t\t\t\t<li><a href=\"#\"><small>무료나눔</small></a></li>\n");
      out.write("\t\t\t\t<li><a href=\"#\"><small>알바모집</small></a></li>\n");
      out.write("\t\t\t\t<li><a href=\"#\"><small>원룸광고</small></a></li>\n");
      out.write("\t\t\t\t<li><a href=\"#\"><small>고객센터</small></a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t\t\t<!-- 자바스크립트로 if문을 사용하여 로그인되었는지 안되었는지를 구분 -->\n");
      out.write("\t\t\t\t");

					//로그인이 되어있으면
					if (userid != null && !userid.equals("")) {
				
      out.write("\n");
      out.write("\t\t\t\t<li><a href=\"#\"> <span class=\"glyphicon glyphicon-user\"></span>&nbsp;<small>");
      out.print(username);
      out.write("&nbsp;님</small>\n");
      out.write("\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"#\"> <span class=\"glyphicon glyphicon-send\"></span>&nbsp;<small>&nbsp;쪽지</small>\n");
      out.write("\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"./logout_proc.jsp\"> <span\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-out\"></span>&nbsp;<small>로그아웃</small>\n");
      out.write("\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t");

					//로그인이 되어있지 않다면
					} else {
				
      out.write("\n");
      out.write("\t\t\t\t<li><a data-toggle=\"modal\" href=\"#loginModal\"> <span\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-in\"></span>&nbsp;<small>로그인</small>\n");
      out.write("\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t<li><a data-toggle=\"modal\" href=\"#joinModal\"> <span\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-plus\"></span>&nbsp;<small>회원가입</small>\n");
      out.write("\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</nav>\n");
      out.write("<!-- 네비게이션바 : 끝 -->\n");
      out.write("\n");
      out.write("<!-- 로그인모달 : 시작 -->\n");
      out.write("<div class=\"modal fade\" id=\"loginModal\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("\taria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("\t<form name=\"login_form\" method=\"post\" class=\"form-horizontal\"\n");
      out.write("\t\trole=\"form\">\n");
      out.write("\t\t<input type=\"hidden\" name=\"pageName\" value=");
      out.print(pageName);
      out.write(">\n");
      out.write("\t\t<div class=\"modal-dialog\">\n");
      out.write("\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("\t\t\t\t\t\taria-hidden=\"true\">×</button>\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\">\n");
      out.write("\t\t\t\t\t\t<span class=\"glyphicon glyphicon-log-in\"></span>&nbsp;LOGIN\n");
      out.write("\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"inputId\" class=\"col-lg-3 control-label\">회원 ID</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-6\">\n");
      out.write("\t\t\t\t\t\t\t<input name=\"userid\" type=\"text\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"User ID\" tabindex=\"1\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-3\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" tabindex=\"4\"><h6>아이디 찾기</h6></a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<label for=\"inputPassword1\" class=\"col-lg-3 control-label\">비밀번호</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-6\">\n");
      out.write("\t\t\t\t\t\t\t<input name=\"password\" type=\"password\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Password\" tabindex=\"2\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-3\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" tabindex=\"5\"><h6>비밀번호 찾기</h6></a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\"\n");
      out.write("\t\t\t\t\t\ttabindex=\"6\">취소</button>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\"\n");
      out.write("\t\t\t\t\t\tonclick=\"login_check()\" tabindex=\"3\">로그인</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</form>\n");
      out.write("</div>\n");
      out.write("<!-- 로그인모달 : 끝 -->\n");
      out.write("\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<!-- CSS -->\r\n");
      out.write("<link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/style-kustom.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./assets/css/docs.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("a:link {\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:visited {\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover {\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- script -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/member.js\"></script>\r\n");
      out.write("<script src=\"./assets/js/holder.js\"></script>\r\n");
      out.write("<script src=\"./assets/js/application.js\"></script>\r\n");
      out.write("<!-- jQuery Version 1.11.0 -->\r\n");
      out.write("<script src=\"js/jquery-1.11.0.js\"></script>\r\n");
      out.write("<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tif (navigator.userAgent.match(/IEMobile\\/10\\.0/)) {\r\n");
      out.write("\t\tvar msViewportStyle = document.createElement(\"style\");\r\n");
      out.write("\t\tmsViewportStyle.appendChild(document\r\n");
      out.write("\t\t\t\t.createTextNode(\"@-ms-viewport{width:auto!important}\"));\r\n");
      out.write("\t\tdocument.getElementsByTagName(\"head\")[0].appendChild(msViewportStyle);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 모바일화면 출력용 -->\r\n");
      out.write("<!-- \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar mobileKeyWords = new Array('iPhone', 'iPod', 'BlackBerry', 'Android', 'Windows CE', 'LG', 'MOT', 'SAMSUNG', 'SonyEricsson');\r\n");
      out.write("\tfor ( var word in mobileKeyWords) {\r\n");
      out.write("\t\tif (navigator.userAgent.match(mobileKeyWords[word]) != null) {\r\n");
      out.write("\t\t\tlocation.href = \"접근경로지정\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script> \r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 페이지 바디 : 시작 -->\r\n");
      out.write("\t<div class=\"container bs-docs-container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t<div class=\"bs-sidebar hidden-print\" role=\"complementary\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav bs-sidenav\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"./index.jsp\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"./event.jsp\">이벤트</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"./accuse.jsp\">불량/사기신고</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<h5 class=\"page-header\" style=\"height: 55\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"new\" src=\"./images/new.png\"><b>이벤트</b><br>\r\n");
      out.write("\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<small>무료체험, 수수료할인, 쿠폰 등 다양한 이벤트!</small>\r\n");
      out.write("\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t<table class=\"table table-condensed table-hover\">\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"60\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"*\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"130\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"70\">\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"text-center\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"font-weight: bolder; background-image: url('./images/table_mid.gif');\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><small></small></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><small>제목</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><small>작성자</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><small>작성일</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><small>조회</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><img alt=\"notice\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"./images/notice.jpg\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\"><a href=\"#\"><small>제목</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><a href=\"#\"><small>관리자</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>2014-08-16</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>30</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><img alt=\"notice\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"./images/notice.jpg\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\"><a href=\"#\"><small>제목</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><a href=\"#\"><small>관리자</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>2014-08-15</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>30</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><img alt=\"notice\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"./images/notice.jpg\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\"><a href=\"#\"><small>제목</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><a href=\"#\"><small>관리자</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>2014-08-14</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>30</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><img alt=\"notice\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"./images/notice.jpg\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\"><a href=\"#\"><small>제목</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><a href=\"#\"><small>관리자</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>2014-08-13</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>30</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><img alt=\"notice\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"./images/notice.jpg\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\"><a href=\"#\"><small>제목</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><a href=\"#\"><small>관리자</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>2014-08-12</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>30</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><img alt=\"notice\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"./images/notice.jpg\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\"><a href=\"#\"><small>제목</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><a href=\"#\"><small>관리자</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>2014-08-11</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>30</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><img alt=\"notice\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"./images/notice.jpg\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\"><a href=\"#\"><small>제목</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><a href=\"#\"><small>관리자</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>2014-08-10</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>30</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><img alt=\"banner_bottom\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"./images/joonggonara_cleancall_banner.jpg\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 100%;\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t<div style=\"margin-top: 20%\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><img alt=\"banner_right\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"./images/banner_right.jpg\" style=\"width: 100%\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 페이지 바디 : 끝 -->\r\n");
      out.write("\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<!-- 꼬릿말 : 시작 -->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t<p>Copyright &copy; Your Website 2014</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 꼬릿말 : 끝 -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
