/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2014-08-24 10:30:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.src;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/src/./include/header.jsp", Long.valueOf(1408872000886L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("EUC-KR");

	//로그인 체크
	String userid = "";
	String username = "";
	userid = (String) session.getAttribute("userid");
	username = (String) session.getAttribute("username");

	//현재 페이지의 파일명 체크

	String cururl = request.getRequestURI().toString();
	String pageName = cururl.substring(cururl.lastIndexOf("/") + 1,
			cururl.length());
	session.setAttribute("pageName", pageName);

	if ((!pageName.equals("index.jsp"))&& userid==null) {

      out.write("\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\talert(\"로그인이 필요한 서비스입니다\");\r\n");
      out.write("\t\t\tlocation.href=\"./index.jsp\";\r\n");
      out.write("\t\t</script>\r\n");

	}

      out.write("\r\n");
      out.write("<a class=\"sr-only\" href=\"#content\">네비게이션 건너뛰기</a>\r\n");
      out.write("<!-- 네비게이션바 : 시작 -->\r\n");
      out.write("<header class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<!-- 모바일 크기일 때 네비게이션바를 한버튼으로 몰아 넣는 기능(타겟의 id값에 해당되는 목록을 출력해준다) -->\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\tdata-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"./index.jsp\">HOME</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- id를 주어 자바스크립트로 모바일 화면에서 네비바버튼이 동작되게 한다 -->\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\"\r\n");
      out.write("\t\t\tid=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li ");
if (pageName.equals("junggo.jsp")) {
      out.write(" class=\"active\" ");
}
      out.write("><a\r\n");
      out.write("\t\t\t\t\thref=\"#\"><small>전국중고시장</small></a></li>\r\n");
      out.write("\t\t\t\t<li ");
if (pageName.equals("board.jsp")) {
      out.write(" class=\"active\" ");
}
      out.write("><a\r\n");
      out.write("\t\t\t\t\thref=\"./board.jsp\"><small>대학중고시장</small></a></li>\r\n");
      out.write("\t\t\t\t<li ");
if (pageName.equals("divide.jsp")) {
      out.write(" class=\"active\" ");
}
      out.write("><a\r\n");
      out.write("\t\t\t\t\thref=\"#\"><small>무료나눔</small></a></li>\r\n");
      out.write("\t\t\t\t<li ");
if (pageName.equals("job.jsp")) {
      out.write(" class=\"active\" ");
}
      out.write("><a\r\n");
      out.write("\t\t\t\t\thref=\"#\"><small>알바모집</small></a></li>\r\n");
      out.write("\t\t\t\t<li ");
if (pageName.equals("room.jsp")) {
      out.write(" class=\"active\" ");
}
      out.write("><a\r\n");
      out.write("\t\t\t\t\thref=\"#\"><small>원룸광고</small></a></li>\r\n");
      out.write("\t\t\t\t<li ");
if (pageName.equals("helpcenter.jsp")) {
      out.write(" class=\"active\"\r\n");
      out.write("\t\t\t\t\t");
}
      out.write("><a href=\"#\"><small>고객센터</small></a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<!-- 자바스크립트로 if문을 사용하여 로그인되었는지 안되었는지를 구분 -->\r\n");
      out.write("\t\t\t\t");

					//로그인이 되어있으면
					if (userid != null && !userid.equals("")) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"> <span class=\"glyphicon glyphicon-user\"></span>&nbsp;<small>");
      out.print(username);
      out.write("&nbsp;님</small>\r\n");
      out.write("\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"> <span class=\"glyphicon glyphicon-send\"></span>&nbsp;<small>&nbsp;쪽지</small>\r\n");
      out.write("\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"./logout_proc.jsp\"> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-out\"></span>&nbsp;<small>로그아웃</small>\r\n");
      out.write("\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t");

					//로그인이 되어있지 않다면
					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li><a data-toggle=\"modal\" href=\"#loginModal\"> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-in\"></span>&nbsp;<small>로그인</small>\r\n");
      out.write("\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t<li><a data-toggle=\"modal\" href=\"#joinModal\"> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-plus\"></span>&nbsp;<small>회원가입</small>\r\n");
      out.write("\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t<form class=\"navbar-form navbar-right\" role=\"search\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group input-group\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Search\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"input-group-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-default\">검색</button>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>\r\n");
      out.write("<!-- 네비게이션바 : 끝 -->\r\n");
      out.write("\r\n");
      out.write("<!-- 페이지 헤더 : 시작 -->\r\n");
      out.write("<div class=\"bs-header\" id=\"content\">\r\n");
      out.write("\t<div class=\"marketing-section marketing-section-signup\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t<h1 class=\"heading\" style=\"font-family: 'Nanum Pen Script', serif;\">대학생을\r\n");
      out.write("\t\t\t\t\t위한 중고시장</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 페이지 헤더 : 끝 -->\r\n");
      out.write("\r\n");
      out.write("<!-- 로그인모달 : 시작 -->\r\n");
      out.write("<div class=\"modal fade\" id=\"loginModal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\taria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t<form name=\"login_form\" method=\"post\" class=\"form-horizontal\"\r\n");
      out.write("\t\trole=\"form\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"pageName\" value=");
      out.print(pageName);
      out.write(">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-hidden=\"true\">×</button>\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"glyphicon glyphicon-log-in\"></span>&nbsp;LOGIN\r\n");
      out.write("\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"inputId\" class=\"col-lg-3 control-label\">회원 ID</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"userid\" type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"User ID\" tabindex=\"1\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" tabindex=\"4\"><h6>아이디 찾기</h6></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"inputPassword1\" class=\"col-lg-3 control-label\">비밀번호</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"password\" type=\"password\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Password\" tabindex=\"2\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" tabindex=\"5\"><h6>비밀번호 찾기</h6></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\ttabindex=\"6\">취소</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"login_check()\" tabindex=\"3\">로그인</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 로그인모달 : 끝 -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"joinModal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\taria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t<form name=\"join\" method=\"post\" class=\"form-horizontal\" role=\"form\"\r\n");
      out.write("\t\tautocomplete=\"off\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-hidden=\"true\">×</button>\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"glyphicon glyphicon-plus\"></span>&nbsp;Join In\r\n");
      out.write("\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 회원 아이디 : 시작 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"col-lg-3 control-label\">회원 ID</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"userid\" id=\"userid\" type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"ime-mode: inactive\" onkeyup=\"ajaxSend('id',this)\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span name=\"id_result\" id=\"id_result\" style=\"color: red\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</h6>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<span name=\"idTxt\" id=\"idTxt\" style=\"display: none;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <input class=\"btn btn-default btn-xs\" type=\"button\" value=\"ID 중복체크\" style=\"margin-top: 5px\" onclick=\"openIDCheck()\"> -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 회원 아이디 : 끝 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 비밀번호 : 시작 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"col-lg-3 control-label\">비밀번호</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"password1\" id=\"password1\" type=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" style=\"ime-mode: inactive\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonkeyup=\"checkpwd()\" placeholder=\"Password\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"col-lg-3 control-label\">비밀번호 확인</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"password2\" id=\"password2\" type=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" style=\"ime-mode: inactive\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonkeyup=\"checkpwd()\" placeholder=\"Check Password\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span name=\"pw_result\" id=\"pw_result\" style=\"color: red;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</h6>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<span name=\"pwTxt\" id=\"pwTxt\" style=\"display: none;\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 비밀번호 : 끝 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 닉네임 : 시작 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"col-lg-3 control-label\">닉네임</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"username\" id=\"username\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" onkeyup=\"ajaxSend('name')\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span name=\"name_result\" id=\"name_result\" style=\"color: red;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</h6>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<span name=\"nameTxt\" id=\"nameTxt\" style=\"display: none;\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 닉네임 : 끝 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 주소 : 시작 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"col-lg-3 control-label\">우편번호</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"zipcode\" id=\"zipcode\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"버튼을 눌러주세요\" readonly>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-default btn-default\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"주소 찾기\" onclick=\"goFindZipcode()\"> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"hidden\" name=\"addTxt\" id=\"addTxt\" value=\"N\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"col-lg-3 control-label\">주소</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-9\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"address1\" id=\"address1\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"필수 정보입니다\" readonly>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"col-lg-3 control-label\">상세주소</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-7\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"address2\" type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"ime-mode: active\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 주소 : 끝 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 이메일 : 시작 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"col-lg-3 control-label\">이메일</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"email\" id=\"email\" type=\"email\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonkeyup=\"ajaxSend('email')\" placeholder=\"비밀번호 찾기에 사용\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span name=\"email_result\" id=\"email_result\" style=\"color: red;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</h6>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<span name=\"emailTxt\" id=\"emailTxt\" style=\"display: none;\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 이메일 : 끝 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 연락처 : 시작 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"col-lg-3 control-label\">연락처</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- OnKeypress=\"onlyNumber()\" style=\"ime-mode:disabled\" onKeyup=\"eng(this)\" -->\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"phone\" id=\"phone\" type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"필수 정보입니다\" readonly>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"btn btn-default btn-default\" type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"휴대폰 인증\" onclick=\"goChkPhone()\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 연락처 : 끝 -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">취소</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" onclick=\"goJoin()\">회원가입</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- script -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/member.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/ajax.js\"></script>");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<!-- <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"> -->\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no\">\r\n");
      out.write("<!-- <meta name=\"description\" content=\"\">\r\n");
      out.write("<!-- <meta name=\"author\" content=\"\"> -->\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<!-- CSS -->\r\n");
      out.write("<link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/style-kustom.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./assets/css/docs.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("a:link {\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:visited {\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover {\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- script -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/member.js\"></script>\r\n");
      out.write("<script src=\"./assets/js/holder.js\"></script>\r\n");
      out.write("<script src=\"./assets/js/application.js\"></script>\r\n");
      out.write("<!-- jQuery Version 1.11.0 -->\r\n");
      out.write("<script src=\"js/jquery-1.11.0.js\"></script>\r\n");
      out.write("<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tif (navigator.userAgent.match(/IEMobile\\/10\\.0/)) {\r\n");
      out.write("\t\tvar msViewportStyle = document.createElement(\"style\");\r\n");
      out.write("\t\tmsViewportStyle.appendChild(document\r\n");
      out.write("\t\t\t\t.createTextNode(\"@-ms-viewport{width:auto!important}\"));\r\n");
      out.write("\t\tdocument.getElementsByTagName(\"head\")[0].appendChild(msViewportStyle);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 모바일화면 출력용 -->\r\n");
      out.write("<!-- \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar mobileKeyWords = new Array('iPhone', 'iPod', 'BlackBerry', 'Android', 'Windows CE', 'LG', 'MOT', 'SAMSUNG', 'SonyEricsson');\r\n");
      out.write("\tfor ( var word in mobileKeyWords) {\r\n");
      out.write("\t\tif (navigator.userAgent.match(mobileKeyWords[word]) != null) {\r\n");
      out.write("\t\t\tlocation.href = \"접근경로지정\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script> \r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 페이지 바디 : 시작 -->\r\n");
      out.write("\t<div class=\"container bs-docs-container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t<div class=\"bs-sidebar hidden-print\" role=\"complementary\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav bs-sidenav\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"./index.jsp\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"./event.jsp\">이벤트</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"./accuse.jsp\">불량/사기신고</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<h5 class=\"page-header form-control\" style=\"height: 55\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"new\" src=\"./images/new.png\"><b>공지사항</b><br>\r\n");
      out.write("\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<small>가입 후\r\n");
      out.write("\t\t\t\t\t\t\t공지사항을 꼭 읽어주세요.</small>\r\n");
      out.write("\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t<table class=\"table table-condensed table-hover\">\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"60\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"*\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"130\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"70\">\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"text-center\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"font-weight: bolder; background-image: url('./images/table_mid.gif');\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><small></small></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><small>제목</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><small>작성자</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><small>작성일</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><small>조회</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><img alt=\"notice\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"./images/notice.jpg\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\"><a href=\"#\"><small>제목</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><a href=\"#\"><small>관리자</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>2014-08-16</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>30</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><img alt=\"notice\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"./images/notice.jpg\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\"><a href=\"#\"><small>제목</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><a href=\"#\"><small>관리자</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>2014-08-15</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>30</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><img alt=\"notice\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"./images/notice.jpg\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\"><a href=\"#\"><small>제목</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><a href=\"#\"><small>관리자</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>2014-08-14</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>30</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><img alt=\"notice\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"./images/notice.jpg\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\"><a href=\"#\"><small>제목</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><a href=\"#\"><small>관리자</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>2014-08-13</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>30</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><img alt=\"notice\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"./images/notice.jpg\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\"><a href=\"#\"><small>제목</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><a href=\"#\"><small>관리자</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>2014-08-12</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>30</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><img alt=\"notice\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"./images/notice.jpg\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\"><a href=\"#\"><small>제목</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><a href=\"#\"><small>관리자</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>2014-08-11</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>30</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><img alt=\"notice\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"./images/notice.jpg\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"left\"><a href=\"#\"><small>제목</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><a href=\"#\"><small>관리자</small></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>2014-08-10</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\"><small>30</small></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><img alt=\"banner_bottom\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"./images/joonggonara_cleancall_banner.jpg\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 100%;\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t<div style=\"margin-top: 20%\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><img alt=\"banner_right\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"./images/banner_right.jpg\" style=\"width: 100%\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 페이지 바디 : 끝 -->\r\n");
      out.write("\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<!-- 꼬릿말 : 시작 -->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t<p>Copyright &copy; Your Website 2014</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 꼬릿말 : 끝 -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
